import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import NewsLetter from "@/components/newsletter/NewsLetter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CartZilla",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <NewsLetter />
        <Footer />
      </body>
    </html>
  );
}
